### ISSUE TITLE
self hosting?

### ISSUE THREAD

**Issue by Uday-461** [pietz/nonan-feedback#1]

**Comment by Uday-461** [comment]
will self hosting be possible? i have a powerful machine and i dont want the 30mb file limit

**Comment by pietz** [comment]
Hey there,

we currently don't plan a self hosted version because we believe there's an advantage to simplicity and things that just work out of the box. Streamlining deployment for others to host the service is not something we want to invest time in at the moment. That's also because the architecture is not something that could be hosted in a simple container. We have a serverless and distributed setup that allows dynamic scaling for thousands of users. It was built with this goal in mind.

The 30MB limit is just during the preview phase for us to work on supported all formats people throw at us. Once we reached this point, we will address larger datasets and scaling. We will likely increase the dataset size of the free tier to something like 100MB and also plan a pro tier that would allows multiple GB datasets.

The last part is our focus at the moment so we can find a way to monetize the platform. Our vision is a tool that can manage huge datasets while taking the hassle of working with large amounts of data away from the user.
